### ISSUE TITLE
Allow git-trac-command to work with Zsh

### ISSUE THREAD

**Issue by slel** [sagemath/git-trac-command#28]
While `git-trac-command` is currently limited to working with Bash,
I wish it would be possible to make it work with Zsh too.

**Comment by vbraun** [comment]
Not sure I understand; the git-trac launcher is written in Python and doesn't depend on any shell.

**Comment by slel** [comment]
I'm referring to the script `enable.sh` which checks whether
the ambient shell is bash, and aborts otherwise.

https://github.com/sagemath/git-trac-command/blob/master/enable.sh

**Comment by godfrey-cw** [comment]
I ran into a similar issue, but adding `.../git-trac-command/bin` to the path in my `.zshrc` (and `.bashrc`) works.

**Comment by mkoeppe** [comment]
let's close this as a dup of #38.
